.text
.align 0x100
.globl _start0
.type _start0, @function
_start0:  /* The .c32 executable must start with this as its entry point. */
/* 00000000  B8FE4CCD21        mov eax,0x21cd4cfe */
.byte 0xb8, 0xfe, 0x4c, 0xcd, 0x21  /* COM32R signature. */
cld

/* Autogenerated relocation instructions in the form of
 * `add [dword ebx + ...], ebx'. Empty for during the first invocation.
 */
/*.include "reloc.s"*/

/* We copy useful function pointers and input variables Syslinux
 * provides us by the COM32R ABI (details:
 * http://www.syslinux.org/doc/comboot.txt ) to our csargs_all.
 *
 * The layout of csargs_all is found in `struct csargs_all' in
 * include/tinyc32.h .
 */
lea 8(%esp), %esi
lea csargs_all, %edi
mov 16(%esp), %eax
shr $4, %eax
/* Fill csargs_all.cs_bounce_seg. */
stos %eax, %es:(%edi)  /* .byte 0xab */   /* stosd */
mov $8, %ecx
/* Copy over to csargs_all.cs_cmdline .. .cs_name . */
rep movsd
mov 40(%esp), %esi
add $4, %esi
/* mov csargs_all + 9 * 4, %edi */  /* Not needed, already correct. */
mov $14, %ecx
/* Copy over to csargs_all.lmalloc .. .ms_timer . */
rep movsd

jmp _start  /* Jump to the C function void _start() { ... } by the user. */

.set  csargs_all_size, 23 * 4  /* Not needed, FYI only. */
.comm csargs_all, csargs_all_size, 1
